# Generated by Django 3.1.2 on 2020-11-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Kryminał", "Kryminał"),
                            ("Literatura młodzieżowa", "Literatura młodzieżowa"),
                            ("Literatura obyczajowa", "Literatura obyczajowa"),
                            ("Romans", "Romans"),
                            ("Fantastyka", "Fantastyka"),
                            ("Sensacja", "Sensacja"),
                            ("Literatura faktu", "Literatura faktu"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="author.author",
                    ),
                ),
            ],
        ),
    ]
